### PR TITLE
Convert Authentication component style to match with rest of the links

### PR DESCRIPTION
**Pull request by ArunJose**
This PR addresses issue #77 

Changes

- Convert login/logoff buttons to text links
- The login button text is changed to "Login with Google" to make clear it's apparent to the user that a Google account is required for login.

### CODE REVIEW

**Review by snrelghgub — COMMENTED** [review]
I would suggest to omit 'with Google'; But I think here it's also important to hear what everyone else thinks 👍

**Comment by ArunJose** [comment]
@snrelghgub Thanks for the feedback. I replaced "with Google" with a Google logo. There's still some issue with styling of auth links inside Hamburger menu.

**Comment by snrelghgub** [comment]
@ArunJose nice work dude! You found the best substitution for 'with Google' in my opinion. I found out recently that displaying the Google Logo is also common policy & practice for apps which makes use of Google APIs like ours, and by displaying the Google Logo you are doing exactly that 👍

**Review by snrelghgub — APPROVED** [review]
I'm approving as I think the most important changes are made but if you would like to gather more input or resolve the minor styling issue with authenticated name displayed creating some minor visual flaws & inconsistencies. I would suggest to try & display at the bottom or above the Login/Logout & see how that go 👍

**Pull request merged**
