### PR TITLE
Card component

### LINKED ISSUE #4: Display search results
**User Story Description**
As a End User
I want to see books matching the search criteria displayed in an infinite scroll 
So I can see the book cover thumbnail, title, and author for all matches

**Steps to Follow (optional)**
- [ ] Step #1
- [ ] Step #2
- [ ] Additional steps as necessary

**Additional Considerations**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

### PR DESCRIPTION
**Pull request by ghost**
The Card component doesn't appear on the page because the `volumes` array in CardsList is empty. To test Card, populate the `volumes` array with props for a Card, eg

```js
export default function CardList() {
  const volumes = [{ title: "Foo", authors: ["Bar", "Baz"] }];
  const card = (volume) => <Card {...volume} />;
  return <div>{volumes.map(card)}</div>;
}
```

### CODE REVIEW

**Comment by snrelghgub** [comment]
hello @willnwhite Your PR is linked to the issue "Display Search Results" which requires the books matching the search criteria display in an infinite scroll, but your PR does not resolve the issue. Please review your code or requirements or let me know or anyone else on our team if you need any assistance with resolving your assigned issue 👍

**Comment by ghost** [comment]
Still no infinite scroll but user can see search results on page.

**Comment by ghost** [comment]
Infinite scroll moved to #39 so this branch can be merged now.

**Review by snrelghgub — APPROVED** [review]
I reviewed your PR once again & tested with different inputs & the correct results displays, the requirement is met & that is the most important. However, the 'more' button provides a UX flaw. The problem with it is that after the User clicks on the 'more' button the next batch of results is displayed upwards meaning that the User has to scroll UP to view the next batch of results from bottom to a new ambiguous starting point. If the User wants to view 'more' again, the User will have to scroll back down to the bottom & it is quite inappropriate. I'm approving as I noticed you've already raised the issue #39 which is definitely one possible way to fix that. cheers @willnwhite  👍

**Pull request merged**
