### PR TITLE
add favicon.ico

### PR DESCRIPTION
**Pull request by Guitarhub786**
Project logo is made of two parts. The icon and the text.
For the favicon.ico I have stripped the text portion to display just the icon.
As the text cannot be read anyway (as it is too small) and allows the logo to display larger so it is clearer to see.

image

image

### CODE REVIEW

**Comment by Guitarhub786** [comment]
Added App Books title name - Books Plus.

image

**Comment by ghost** [comment]
That's a nice logo! The favicon looks squashed in the screenshots. [W3C](https://www.w3.org/2005/10/howto-favicon) says it must be 16x16 or 32x32 pixels.

**Comment by Guitarhub786** [comment]
Thank you for raising the issue. I noticed it too. I used the .ico version rather than the 16x16 32x32 png.
However, it does the same choosing 16x and 32x . 

I have looked into it, and the problem is that the logo is a rectangle and "favicon" turns it into a ratio of a square.
Hence the squash look. I am working on the solution. I am recreating a backdrop that is a square and putting the logo into that.
So, hopefully, when I save the "square" backdrop and not the logo, the logo should be in proportion.

**Review by ArunJose — APPROVED** [review]
Confirmed that favicon is displayed properly with correct aspect ratio.

**Pull request merged**
