### PR TITLE
'Loading' message when results loading

### LINKED ISSUE #25: Loading Animation
**User Story Description**
As an End User.
When I search a book and I do not get an immediate response, I would like some response like a loading animation to indicate it is searching and not crashed or something is wrong with my computer.

**Additional Considerations**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

### LINKED ISSUE #52: Indicate to user when more search results are being loaded.
**User Story Description**
As an end user
I want to see a loading icon when I have scrolled to the bottom of the page. 
So I can know that more results are being loaded.

**Additional Considerations**
This is increasingly important for those who have slower connection.

### PR DESCRIPTION
**Pull request by ghost**
Pair programming with @Guitarhub786

### CODE REVIEW

**Comment by ghost** [comment]
Refactoring to do: `setIsLoading(true)` is currently coupled to scrolling to bottom of page (in `handleScroll`), but it needs to be coupled to the HTTP request in `useBookSearch`.

**Review by ArunJose — COMMENTED** [review]
In console there is a warning: ``React Hook useEffect has a missing dependency: 'setIsLoading'. Either include it or remove the dependency array. If 'setIsLoading' changes too often, find the parent component that defines it and wrap that definition in useCallback  react-hooks/exhaustive-deps``

I agree with @willnwhite that this needs refactoring.  It would be a better implementation if `isLoading` state variable is declared inside `useBookSearch.jsx` and returned to `App.jsx`

**Comment by ghost** [comment]
@ArunJose found a bug: scrolling abruptly to the bottom of the page causes multiple page loads/requests. I've attempted to fix this on this branch, using @ArunJose's fix, and can't reproduce the bug. @ArunJose, can you still reproduce the bug, or is it fixed?

**Comment by ghost** [comment]
> In console there is a warning: `React Hook useEffect has a missing dependency: 'setIsLoading'. Either include it or remove the dependency array. If 'setIsLoading' changes too often, find the parent component that defines it and wrap that definition in useCallback react-hooks/exhaustive-deps`
> 
> I agree with @willnwhite that this needs refactoring. It would be a better implementation if `isLoading` state variable is declared inside `useBookSearch.jsx` and returned to `App.jsx`

This is fixed by commit 6ec0771.

**Review by snrelghgub — COMMENTED** [review]
@willnwhite I found a minor flaw while testing. If a query is made & no items are found, the next query if valid will still show up ‘No items found’ while loading/searching. I suggest an onChange handler to reset the error state back to its initial state “” on the next user input/change & before another query is made.

**Comment by ArunJose** [comment]
> @ArunJose found a bug: scrolling abruptly to the bottom of the page causes multiple page loads/requests. I've attempted to fix this on this branch, using @ArunJose's fix, and can't reproduce the bug. @ArunJose, can you still reproduce the bug, or is it fixed?

@willnwhite, I can confirm this bug is fixed now 👍

**Review by ArunJose — APPROVED** [review]
I've reviewed this PR once again. The minor flaw pointed out by @snrelghgub isn't related to this feature, persistence of the error message until the next search is made was intended like that at the time(open for change), and it exists in the `development` branch too.  The position of the search error message should be in place of results, and the error message can be improved too - like replacing `"No results found!"` with `"No results found for your search "previous-search-term"`. Since displaying error message isn't related to this feature(displaying loading message), I believe that shouldn't be reason to not approve this PR.

@willnwhite Since you are using `setAreResultsLoading` within the hook both times, it would be better to declare it within the hook and just return the `areResultsLoading` value to App.js. This will make the parameters of the `useBookSearch` hook consistant and avoid using `setAreResultsLoading` as a dependency for useEffect in `useBookSearch`.  Also, I think organising code like this will make it more modular.

Since the issue with error message raised by @snrelghgub isn't connected with this PR and the feature is working properly, I'm approving this PR.

**Comment by ghost** [comment]
> @willnwhite Since you are using `setAreResultsLoading` within the hook both times, it would be better to declare it within the hook and just return the `areResultsLoading` value to App.js. This will make the parameters of the `useBookSearch` hook consistant and avoid using `setAreResultsLoading` as a dependency for useEffect in `useBookSearch`. Also, I think organising code like this will make it more modular.

Thanks @ArunJose, this is a really nice idea for a refactor.

**Pull request merged**
