### PR TITLE
Feature/display additional book details

### LINKED ISSUE #5: Display additional book details
**User Story Description**
As a End User
I want to click on a book to display additional details
So I can view additional details to help me decide if I want to read it

**Steps to Follow (optional)**
- [ ] Identify additional book details that should be displayed in the search results or when the user clicks on a book in that list
- [ ] Additional steps as necessary

**Additional Considerations**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

### PR DESCRIPTION
**Pull request by mokokom**
Here is a first draft of this feature. I've displayed the book details in a really simple drop-down list for now (no design), but that could change depending on the layout of the card list (modal might be better). If the functionality and general details added are ok with you, I will work on the layout of the cards list, the card's design and from there I should have a better look on how to implement / design the details of the book.

### CODE REVIEW

**Review by snrelghgub — COMMENTED** [review]
nice work dude. I'm working on the design for the Cards / Card List to resolve #20 so practically that means you shouldn't have to worry about that but you might want to consider to pull the latest changes from our development branch & resolve your merge conflicts. I also suggest you replace your div element with a button or hyperlink to display a simple modal with a minimal basic styling like this one perhaps: https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_modal 
After you merge your PR into our development branch we could then raise another issue to fix the styling of your modal in a new PR, I think is best incremental approach in this situation.

**Comment by ghost** [comment]
@mokokom Did you mean to use `webReaderLink` for "preview", rather than `previewLink`? When I search for "search", many of the previews don't work well, but the previewLinks do when I look on https://developers.google.com/books/docs/v1/reference/volumes/list?apix_params=%7B%22q%22%3A%22search%22%7D#try-it.

**Comment by mokokom** [comment]
I updated my branch with all your recommendations and suggestions. I only worked on the features ( no design, it's very ugly so far :) )

**Comment by ArunJose** [comment]
@mokokom Is the "buy for" link supposed to include price like "buy for $30"? In many of the pages, it's linked to the self(same as the deploy link). If price isn't available or the buy link isn't available I think it would be better to remove that link in those cases.

**Review by ghost — APPROVED** [review]
As discussed in today's meeting

**Pull request merged**
