### PR TITLE
Diemention results loading notification

### PR DESCRIPTION
**Pull request by Guitarhub786**
An option to use component 'select/option' instead of 'radio buttons'.
Like the previous 'radio' option, 'select' is set default to 'relevance', and user can change to 'newest' before or after initial search.

### CODE REVIEW

**Comment by ghost** [comment]
Upside: the drop-down takes up less space than the two radio buttons
Downside: the user has to click on the drop-down to see what options they have

**Comment by Guitarhub786** [comment]
A) "Upside: the drop-down takes up less space than the two radio buttons
B) "Downside: the user has to click on the drop-down to see what options they have"

Agreed. My thoughts are if we're going to only have 'two' options for MVP then stick to 'radio' buttons.
But if you intend to add more options, then having dropdowns start to make sense.

**Review by snrelghgub — COMMENTED** [review]
hello @Guitarhub786  thanks for presenting your new alternative way of allowing users to set their search preferences. More ideas are always better than less & coding it & presenting it is also always better than only suggesting, Awesome job again! I don't think at this point your proposed solution should be implemented under to the search bar. The user would need to take two steps to apply a non-default preference instead of just one (less work for the user provides a better UX) & I believe @willnwhite has already implemented the best solution in our 'current' situation. However, if we had more options, if we didn't want to clutter the interface I think your proposal would definitely be one of best possible ways to resolve that. So, thanks for writing some of the code for it already 👍

**Comment by jdmedlock** [comment]
Closing since it's already implemented from another PR

**Pull request closed without merging**
