### PR TITLE
Bug/absent data handling

### PR DESCRIPTION
**Pull request by mokokom**
@willnwhite  and I have fixed the issue with absent data and how to handle it in frontend during our pair programming. Also @ArunJose mentionned an issue with unsecure image link URL. This PR resolve this too by changing all image URL from HTTP to HTTPS.

### CODE REVIEW

**Comment by ArunJose** [comment]
image

On details page author info and publisher info are missing but it's shown in the card component. 

Absent data handling on the card component works good. 

image

Here are a few things I've noticed with the image:
- There is some grey area on the top and bottom of the image when the image size is smaller like in the first card.
- Instead of just showing a "image not available" I personally think it'd be better to show a placeholder image like [this](http://lgimages.s3.amazonaws.com/gc-md.gif), or display nothing at all. Of course this is just preference

One other improvement that could be made is changing date format. It seems unclear what 1988/1/2 could mean. A better format would be like "2 Jan 1988".

In deploy preview the image links still aren't updated, it's still requesting http images and the warnings are still shown in console.

**Comment by ghost** [comment]
A search for "dragon force" shows that this fixes linked issue #72. I'm happy for this to be merged.

**Comment by mokokom** [comment]
thank you for your feedback. @ArunJose, I will fix the issues you've mentioned. About HTTP URLs I made a mistake in calling the method on infoLink and I only called it in the Modal component and not in Cart. I think this should be fixed at the next PR.

**Comment by mokokom** [comment]
@ArunJose I added your suggestions and fixed the issues you mentioned. Let me know if you still see any issues 
Capture d’écran 2020-11-11 à 16 23 46
Capture d’écran 2020-11-11 à 16 23 26

**Comment by mokokom** [comment]
There is a lot of conflict with the new merge in the development branch. They are based on @ArunJose 's latest feature, maybe we should resolve the conflicts together?

**Review by ArunJose — APPROVED** [review]
@mokokom All the issues I mentioned are fixed and improvements look good. Nice job!

**Pull request merged**
