### PR TITLE
Feature/infinite scroll search results

### LINKED ISSUE #39: Infinite scroll search results
**User Story Description**
As an end user
I want to scroll down to load more search results
So I can see more search results with less effort than clicking a "load more results button"

**Additional Considerations**
Example of infinite scroll: https://infinite-scroll.com/demo/full-page/page3.html

### PR DESCRIPTION
**Pull request by ghost**
Though there are UI enhancements to make, like showing that results are loading, I thought I'd PR this now since the basic feature is working (and therefore offers value to the user). More commits could be made on this branch to make those enhancements, and then they could be merged into development subsequently. It would just save opening up another branch for the UI enhancements.

### CODE REVIEW

**Comment by ArunJose** [comment]
Infinite scrolling is working properly in Firefox.

I couldn't get infinite scrolling working in Chrome, both in live predeployment, and when running locally. No infinite scrolling occurs with live predeployment and infinite scrolling stops at second page when running locally. I'm not sure whether the issue is specific to my installation of Chrome, we need to check it with other team members.

**Review by snrelghgub — COMMENTED** [review]
hello @willnwhite I probably wouldn't have noticed it if I didn't see @ArunJose's comment but to be more informative, here's the error I got after scrolling a few pages on Microsoft Edge: 
useBookSearch-bug
The infinite scrolling also broke the app in Google Chrome on Android 10.
It appears to me that the problem is occurring in the custom hook useBookSearch. @ArunJose did you notice the Type error appearing in the console coming from the useBookSearch custom hook?

**Comment by ArunJose** [comment]
Hi, @snrelghgub. I didn't come across that error. For me, on Microsoft Edge, infinite scrolling isn't working. Are you getting this error on all searches or only on specific searches? I would like to reproduce that error to look it into further and to check whether that bug exists also in `development` branch.

**Comment by snrelghgub** [comment]
@ArunJose I used very basic input test strings "test", "javascript" - everything seem to work fine until I attempt to rapidly scroll down a few pages but then the app breaks & all I see is a blank HTML page & the Type error message in the console. when you say that the infinite scrolling doesn't work on your side. can you elebarote exactly what happens? do you get a blank landing page too? what do you see in the console?

**Comment by ArunJose** [comment]
@snrelghgub When I say infinite scrolling doesn't work for me in Microsoft Edge, I mean only the first search page is loading and it doesn't load the next page on scrolling to the bottom. And I don't see the TypeError warning in console when scrolling to the bottom. The app works as expected but only shows first 40 items i.e. without infinite scrolling

But I was able to replicate this bug in `development` branch (on Chrome)  with search term "test" and clicking on `more` button repeatedly. I will work on a fix for this bug. Thank you for reporting this.

**Review by snrelghgub — APPROVED** [review]

**Comment by ghost** [comment]
> Infinite scrolling is working properly in Firefox.
> 
> I couldn't get infinite scrolling working in Chrome, both in live predeployment, and when running locally. No infinite scrolling occurs with live predeployment and infinite scrolling stops at second page when running locally. I'm not sure whether the issue is specific to my installation of Chrome, we need to check it with other team members.

@ArunJose Did #50 fix this too?

**Pull request merged**
